### ISSUE TITLE
Feature Request: Channel Support

### ISSUE THREAD

**Issue by dannyhanes** [jellyfin/jellyfin-plugin-pushbullet#2]
I would love to be able to send a push to a specific channel. I have one for Plex, Home Assistant etc. Would love to create one for Jellyfin.

**Comment by joshuaboniface** [comment]
@Nickbert7 Are you interested in implementing this? If you'd like to take the goahead on this repo I can give you perms to do so.

**Comment by Nickbert7** [comment]
Unfortunately I have no experience with C#...
I'm still struggling to get the plugin working for 10.3.6 and 10.3.7 again
Pushing to a specific channel should basically work as it is just an additional target parameter
https://docs.pushbullet.com/#target-parameters

**Comment by Nickbert7** [comment]
@dannyhanes Could you please try version 2 of the plugin.
You should be able to push into a channel now.

**Comment by dannyhanes** [comment]
@Nickbert7 Hey, sorry for the delayed response. Everything is working great! Thank you so much for getting this resolved.
