### ISSUE TITLE
Jellyfin Crashing Pushbullet 3.0.0.0 (Release)

### ISSUE THREAD

**Issue by matda59** [jellyfin/jellyfin-plugin-pushbullet#9]
Jellyfin Version: 10.5.0
Operating System: Windows 10
Architecture: X64

After installing Pushbullet 3.0.0.0 (Release) the Jellfin Console closes and when i restart it crashes with the below error.

![image](https://user-images.githubusercontent.com/27712001/79855161-edf63b80-840d-11ea-906d-6d545be57012.png)

**Comment by Bond-009** [comment]
You are trying to run a plugin for Jellyfin 10.5.2 on Jellyfin 10.5.0

**Comment by matda59** [comment]
thanks - upgraded to 10.5.2 was able to install. however still getting "There was an error sending the test notification. Please check your notification settings and try again"
